%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-rosidl-generator-py
Version:        0.24.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rosidl_generator_py package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       python%{python3_pkgversion}-numpy
Requires:       ros-kilted-ament-cmake
Requires:       ros-kilted-ament-cmake-cppcheck
Requires:       ros-kilted-ament-cmake-cpplint
Requires:       ros-kilted-ament-cmake-flake8
Requires:       ros-kilted-ament-cmake-pep257
Requires:       ros-kilted-ament-cmake-uncrustify
Requires:       ros-kilted-ament-index-python
Requires:       ros-kilted-rmw
Requires:       ros-kilted-rosidl-cli
Requires:       ros-kilted-rosidl-generator-c
Requires:       ros-kilted-rosidl-parser
Requires:       ros-kilted-rosidl-pycommon
Requires:       ros-kilted-rosidl-runtime-c
Requires:       ros-kilted-rosidl-typesupport-c
Requires:       ros-kilted-rosidl-typesupport-interface
Requires:       ros-kilted-rpyutils
Requires:       ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-rosidl-runtime-c
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-kilted-rosidl-generator-packages(member)
Provides:       ros-kilted-rosidl-runtime-packages(member)

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-numpy
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-ament-cmake-pytest
BuildRequires:  ros-kilted-ament-index-python
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-ament-lint-common
BuildRequires:  ros-kilted-rmw
BuildRequires:  ros-kilted-rosidl-cmake
BuildRequires:  ros-kilted-rosidl-generator-c
BuildRequires:  ros-kilted-rosidl-generator-cpp
BuildRequires:  ros-kilted-rosidl-parser
BuildRequires:  ros-kilted-rosidl-typesupport-c
BuildRequires:  ros-kilted-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-kilted-rosidl-typesupport-introspection-c
BuildRequires:  ros-kilted-rpyutils
BuildRequires:  ros-kilted-test-interface-files
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-kilted-rosidl-generator-packages(all)
Supplements:    ros-kilted-rosidl-runtime-packages(all)
%endif

%description
Generate the ROS interfaces in Python.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Mon Oct 06 2025 Dharini Dutia <dharini@openrobotics.org> - 0.24.2-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Dharini Dutia <dharini@openrobotics.org> - 0.24.1-2
- Autogenerated by Bloom

* Fri Apr 18 2025 Dharini Dutia <dharini@openrobotics.org> - 0.24.1-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Dharini Dutia <dharini@openrobotics.org> - 0.24.0-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Dharini Dutia <dharini@openrobotics.org> - 0.23.1-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Dharini Dutia <dharini@openrobotics.org> - 0.23.0-1
- Autogenerated by Bloom

* Tue Apr 16 2024 Dharini Dutia <dharini@openrobotics.org> - 0.22.0-1
- Autogenerated by Bloom

* Thu Mar 28 2024 Dharini Dutia <dharini@openrobotics.org> - 0.21.2-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Dharini Dutia <dharini@openrobotics.org> - 0.21.1-2
- Autogenerated by Bloom

